esphome:
  name: hpc
  friendly_name: Heat Pump Controller
  min_version: 2025.5.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://reekhout/itho_daalderop_hp-s@v0.0.1
    refresh: 0s

uart:
  baud_rate: 19200
  rx_pin: GPIO20
  parity: ODD

modbus_monitor:
  id: modbusmonitor
  log_not_configured_data: false

sensor:
  - platform: modbus_monitor
    device_address: 0x0B
    register_address: 41200
    name: Room temperature (Tr)
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - offset: -3000
      - multiply: 0.01
      - delta: 0.01
  - platform: modbus_monitor
    device_address: 0x0B
    register_address: 41202
    name: Cooling/heating water temperature (Tc)
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - offset: -3000
      - multiply: 0.01
      - delta: 0.01
  - platform: modbus_monitor
    device_address: 0x0B
    register_address: 41203
    name: Heat exchanger water outlet temperature (Tuo)
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - offset: -3000
      - multiply: 0.01
      - delta: 0.01
    on_value:
      then:
        - sensor.template.publish:
            id: heat_exchanger_d_t
            state: !lambda |-
              return x - id(heat_exchanger_water_inlet_temperature).state;
  - platform: modbus_monitor
    device_address: 0x0B
    register_address: 41204
    id: heat_exchanger_water_inlet_temperature
    name: Heat exchanger water inlet temperature (Tui)
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - offset: -3000
      - multiply: 0.01
      - delta: 0.01
  - platform: template
    id: heat_exchanger_d_t
    name: Heat exchanger ΔT
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
  - platform: modbus_monitor
    device_address: 0x0B
    register_address: 41205
    name: Indoor coil temperature (Tup)
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - offset: -3000
      - multiply: 0.01
      - delta: 0.01
  - platform: modbus_monitor
    device_address: 0x0B
    register_address: 41304
    id: circulation_pump_speed
    state_class: "measurement"
    filters:
      - delta: 1
    on_value:
      then:
        - text_sensor.template.publish:
            id: circulation_pump
            state: !lambda |-
              switch ((int)x)
              {
                case 1000:
                  return "Off";
                case 500:
                  return "Low speed";
                case 250:
                  return "Medium speed";
                default:
                  return "High speed";
              }
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42101
    name: Outdoor voltage
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 0
    filters:
      - delta: 1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42102
    name: Outdoor current
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - delta: 0.1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42103
    name: Compressor speed setpoint
    unit_of_measurement: Hz
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 0
    filters:
      - delta: 1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42104
    name: Compressor speed
    unit_of_measurement: Hz
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 0
    filters:
      - delta: 1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42105
    name: Fan speed setpoint
    unit_of_measurement: rpm
    state_class: measurement
    icon: mdi:fan
    accuracy_decimals: 0
    filters:
      - delta: 1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42106
    name: Fan speed
    unit_of_measurement: rpm
    state_class: measurement
    icon: mdi:fan
    accuracy_decimals: 0
    filters:
      - delta: 1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42108
    name: EEV opening
    unit_of_measurement: P
    state_class: measurement
    icon: mdi:arrow-expand
    filters:
      - delta: 1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42111
    name: Ambient temperature (Ta)
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - offset: -3000
      - multiply: 0.01
      - delta: 0.01
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42112
    name: Outdoor coil temperature (Tp)
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - offset: -3000
      - multiply: 0.01
      - delta: 0.01
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42113
    name: Discharge temperature (Td)
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - offset: -3000
      - multiply: 0.01
      - delta: 0.01
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42114
    name: Suction temperature (Ts)
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - offset: -3000
      - multiply: 0.01
      - delta: 0.01
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42117
    name: Low pressure (Ps)
    unit_of_measurement: bar
    device_class: pressure
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - delta: 0.1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42118
    name: High pressure (Pd)
    unit_of_measurement: bar
    device_class: pressure
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - delta: 0.1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42109
    id: defrost_value1
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42119
    id: defrost_value2
  - platform: modbus_monitor
    device_address: 0x02
    register_address: 42120
    id: defrost_value3
  - platform: wifi_signal
    id: wifi_signal_db
    name: WiFi signal

binary_sensor:
  - platform: modbus_monitor
    device_address: 0x0B
    register_address: 41214
    name: Cooling switch
    icon: mdi:snowflake
  - platform: modbus_monitor
    device_address: 0x0B
    register_address: 41215
    name: Heating switch
    icon: mdi:fire
  - platform: modbus_monitor
    device_address: 0x0B
    register_address: 41306
    id: diverter_valve
    trigger_on_initial_state: true
    on_state:
      then:
        - text_sensor.template.publish:
            id: diverter_valve_text
            state: !lambda |
              if (x)
                return "Cooling/Heating";
              else
                return "Domestic hot water";
  - platform: modbus_monitor
    name: Auxiliary electrical heater
    icon: mdi:heat-wave
    device_address: 0x0B
    register_address: 41310
  - platform: template
    name: Defrosting
    icon: mdi:snowflake-melt
    lambda: |-
      return (id(defrost_value1).state == 68 && (id(defrost_value2).state == 1 || id(defrost_value3).state == 2048)) || (id(defrost_value1).state == 4);

text_sensor:
  - platform: template
    id: circulation_pump
    name: Circulation pump
    icon: mdi:pump
  - platform: template
    id: diverter_valve_text
    name: Diverter valve
    icon: mdi:call-split

switch:
  - platform: gpio
    pin: GPIO0
    id: cooling_mode    
    name: Cooling mode
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: heating_mode
  - platform: gpio
    pin: GPIO1
    id: heating_mode
    name: Heating mode
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: cooling_mode
